apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: ncore99/todo-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_DB
