apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: frontend
          image: ncore99/todo-frontend:latest
          ports:
            - containerPort: 3000
